import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Sanity Next Site!",
  description: "Generated by next + sanity",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body className={`${inter.className} max-w-4xl mx-auto py-10 px-5`}>
        <header className="flex justify-between items-center">
          <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-xl font-bold">Erin K.</Link>
          <nav className="flex items-center gap-5 text-sm">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </nav>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
